-- Migration 002: Membership reference tables
--
-- Creates the controlled vocabulary for membership classification.
-- This migration does not modify the existing members table.

CREATE TABLE membership_classes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar NOT NULL UNIQUE,
    name varchar NOT NULL UNIQUE,
    active boolean DEFAULT true
);

CREATE TABLE membership_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar NOT NULL UNIQUE,
    name varchar NOT NULL UNIQUE,
    active boolean DEFAULT true
);

CREATE TABLE full_member_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar NOT NULL UNIQUE,
    name varchar NOT NULL UNIQUE,
    active boolean DEFAULT true
);

-- Initial membership classes

INSERT INTO membership_statuses (id, code, name)
VALUES
    (1, 'ACTIVE', 'Active'),
    (2, 'LEFT', 'Left'),
    (3, 'DECEASED', 'Deceased');

-- Full member types.
-- These apply only when membership_class = FULL.

INSERT INTO full_member_types (id, code, name)
VALUES
    (1, 'STANDARD', 'Standard'),
    (2, 'FTE', 'Full-time education'),
    (3, 'AGE_70_79', 'Age 70-79'),
    (4, 'AGE_80_PLUS', 'Age 80+'),
    (5, 'HLM', 'Honorary life member');
